feat: only re-highlight changed ranges
TorchedSammy/Evergreen.lxl pull request #20
Opened 2022-12-26 16:03 UTC by xcb-xwii

Requires https://github.com/euclidianAce/ltreesitter/pull/12.

2022-12-27 17:59 UTC, TorchedSammy commented on init.lua
> +		for i=p.start_point.row+1,p.end_point.row+1 do
add spacing

2022-12-27 18:00 UTC, TorchedSammy commented on init.lua
> +	do
could you only line break in the table

2022-12-27 18:01 UTC, TorchedSammy commented on init.lua
> +				if (lastName ~= "error") then
braces here not needed

2022-12-27 18:02 UTC, TorchedSammy requested changes
a little bit of style changes but otherwise looks good

2022-12-28 18:23 UTC, TorchedSammy requested changes
actually it seems like this introduces odd artifacts:  
![](https://safe.kashima.moe/80voeh0lqb57.png)

2022-12-28 19:12 UTC, xcb-xwii commented
> actually it seems like this introduces odd artifacts:  
> 
> ![](https://safe.kashima.moe/80voeh0lqb57.png)

Have a fix, will push later

2022-12-29 09:07 UTC, xcb-xwii commented
Resolved the issue with the artefacts, and rebased onto master.

2022-12-29 18:54 UTC, TorchedSammy approved these changes

2022-12-30 12:59 UTC, merged