feat: add Julia support
TorchedSammy/Evergreen.lxl pull request #47
Opened 2023-09-25 12:45 UTC by ShalokShalom

Hi lovely people 😃 

This contribution is supposed to include Julia into the list of supported languages. 
The highlights.scm file got copied from a repo, that uses the Apache 2 license. 

I think this means, we are supposed to add that one to the project.

2023-09-25 13:17 UTC, sammy-ette requested changes

2023-09-25 14:48 UTC, ShalokShalom commented on queries/julia/highlights.scm
> +(command_literal) @string.special
Honestly, I dont know much about scm files and treesitter, feel free to adopt as you see fit. 

I would probably just do something stupid. 😄

2023-09-26 21:47 UTC, TorchedSammy commented on languages.lua
> +	julia = 'https://github.com/tree-sitter/tree-sitter-julia'
missing comma

2023-09-26 21:48 UTC, TorchedSammy commented on queries/julia/highlights.scm
> +(command_literal) @string.special
just change `@string.special` to `@string`?

2023-09-26 21:49 UTC, TorchedSammy commented on queries/julia/highlights.scm
> +
```suggestion

(ERROR) @error
```

2023-09-26 21:49 UTC, TorchedSammy requested changes
some simple changes, and i'll merge

2023-09-26 22:08 UTC, ShalokShalom commented
I think I got everything.

2023-09-26 22:11 UTC, TorchedSammy approved these changes

2023-09-26 22:14 UTC, merged

2026-01-16 15:32 UTC, eitsupi commented
> The highlights.scm file got copied from a repo, that uses the Apache 2 license.

It seems that this file is under MPL-2.0. See lapce/lapce#2640
Would relicensing be a violation of the license?